swagger: '2.0'
info:
  title: ARGENTBANK API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Accounts API
      description: API for fetching user accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User accounts fetch successully
          schema:
            $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/ID/transactions/:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching a user transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for creating a user transaction inforamtions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Create user transaction information
          required: true
          schema:
            $ref: '#/definitions/TransactionCreate'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction created successully !
          schema:
            $ref: '#/definitions/TransactionUpdate'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for updating a user transaction informations
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user transaction informations
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction informations updated successully
          schema:
            $ref: '#/definitions/TransactionUpdate'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: Delete user
      parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: header
            name: ID
            type: string
            required: true
            description: string id of user to delete
      responses:
        '200':
          description: User transaction informations deleted successully !
          schema:
            $ref: '#/definitions/TransactionDelete'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountId:
            type: string
          accountType:
            type: string
          accountNumber:
            type: string
          accountAmount:
            type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            transactionId:
              type: string
            transactionDate:
              type: string
            transactionDescription:
              type: string
            transactionAmount:
              type: string
            transactionBalance:
              type: string
            transactionType:
              type: string
            transactionCategory:
              type: string
            transactionNote:
              type: string
  TransactionCreate:
    type: object
    properties:
      transactionId:
        type: string
      transactionCategorie:
        type: string
      transactionNotes:
              type: string
  TransactionUpdate:
    type: object
    properties:
      transactionId:
        type: string
      transactionCategorie:
        type: string
      transactionNotes:
              type: string
  TransactionDelete:
    type: object
    properties:
      transactionId:
        type: string